# Generated by Django 5.2.5 on 2025-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=True),
        ),
    ]
